name: Publish on Pull Request

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.7]

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      #     - name: Run the tests
      #       run: npm test

      - name: 🔨 Build
        run: CI='' npm run build

      - name: 📂 Sync files to prod folder
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.server }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./dist/
          server-dir: ultimorecurso.omegafox.me/
